// autogenerated file, do not edit

#pragma once

#include <string>

namespace rt3d_tracking{

constexpr std::string_view CONFIG_DIR = "/home/docker/workspace/workspace/src/real-time-3D-tracking/cfg";

constexpr std::string_view RESOURCES_IMAGES = "/home/docker/workspace/workspace/src/real-time-3D-tracking/cfg/../test/inputs/images";
constexpr std::string_view RESOURCES_VIDEOS = "/home/docker/workspace/workspace/src/real-time-3D-tracking/cfg/../test/inputs/videos";

constexpr std::string_view TOPIC_AABB = "aabbs";
constexpr std::string_view TOPIC_IMAGES_COMPRESSED = "images_compressed";
constexpr std::string_view BOPDYPOSE133 = "bodypose133";
constexpr std::string_view KEYPOINT_MARKER = "keypoint_marker";

constexpr std::size_t MAX_INFERENCE_SLEEP_MS = 20;
constexpr std::size_t MAX_INFERENCE_ITER = 10;

constexpr std::size_t N_CLASSES_DETECTIOM = 4;
constexpr std::size_t MIN_CAMS_TRIANGULATION = 3;

} // namespace rt3d_tracking
